name: numerictokanji
description: A new Flutter application.

version: 1.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  span_builder: ^0.1.0
  neumorphic: ^0.3.2
  url_launcher: ^5.4.11




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Noto Serif JP
      fonts:
        - asset: fonts/NotoSerifJP-Medium.otf
          weight: 500
        - asset: fonts/NotoSerifJP-SemiBold.otf
          weight: 600

